# Generated by Django 4.0 on 2021-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nationalCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
