# Generated by Django 4.0 on 2021-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDr', models.IntegerField()),
                ('NationalIDPationt', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=20)),
                ('drugllist', models.CharField(max_length=100)),
            ],
        ),
    ]
